language: objective-c
osx_image: xcode8
cache: 
  directories:
    - vendor/bundle
    - ~/.cocoapods
before_install:
  - gem install bundler
  - bundle install -j4 --path=vendor/bundle --binstubs=vendor/bin
install:
  - cd Example/ios && bundle exec pod install && cd -
script:
  - cd Example/ios && bundle exec rake test:iphonesimulator
